### ISSUE TITLE
std::swap not available in c++98

### ISSUE THREAD

**Issue by jpcima** [martinmoene/any-lite#10]
As documented in the [reference], `std::swap` needs `<algorithm>` prior to C++11.
Building the C++98 version of tests fail in Linux with GCC 12.1.1.

This works by adding the following to `any.hpp`.
```cpp
#if !any_CPP11_OR_GREATER
#include <algorithm>
#endif
```

[reference]: https://en.cppreference.com/w/cpp/algorithm/swap

**Comment by martinmoene** [comment]
Thanks @jpcima, will try to address it this weekend.

**Comment by jpcima** [comment]
This works, thank you.
