### ISSUE TITLE
[isocpp-lib] CH 3, p0032r2 -- let's not have too clever tags

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/any-lite#2]
See [issue at optional](https://github.com/martinmoene/optional-lite/issues/3).

**Comment by lichray** [comment]
This syntax is both clever and simple to me:
```
any(in_place<T or I>(), args...)
```

**Comment by martinmoene** [comment]
See [`in_place`](https://en.cppreference.com/w/cpp/utility/in_place)  at cppreference and [p0032](http://wg21.link/p0032).
